### ISSUE TITLE
OSX Install

### ISSUE THREAD

**Issue by ronag** [brycedrennan/imaginAIry#105]
`pip install imaginairy==6.0.0a0 --upgrade`

Seems to require https://github.com/huggingface/transformers/issues/2831#issuecomment-1001437376

But then:

```
/opt/homebrew/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/opt/homebrew/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: (__ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE)
  Referenced from: '/opt/homebrew/lib/python3.9/site-packages/torchvision/image.so'
  Expected in: '/opt/homebrew/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib'
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 5, in <module>
    from imaginairy.cmds import imagine_cmd
  File "/opt/homebrew/lib/python3.9/site-packages/imaginairy/__init__.py", line 7, in <module>
    from .api import imagine, imagine_image_files  # noqa
  File "/opt/homebrew/lib/python3.9/site-packages/imaginairy/api.py", line 14, in <module>
    from imaginairy.enhancers.describe_image_blip import generate_caption
  File "/opt/homebrew/lib/python3.9/site-packages/imaginairy/enhancers/describe_image_blip.py", line 13, in <module>
    device = get_device()
  File "/opt/homebrew/lib/python3.9/site-packages/imaginairy/utils.py", line 22, in get_device
    if torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'
```

**Comment by brycedrennan** [comment]
Are you on an M1 laptop? what version of torch is installed?

**Comment by brycedrennan** [comment]
Closing until we get more information.

**Comment by ronag** [comment]
torch in /opt/homebrew/lib/python3.9/site-packages (1.11.0)

**Comment by ronag** [comment]
Now I got it running but it just dies:

```
~$ imagine "a scenic landscape" "a photo of a dog" "photo of a fruit bowl" "portrait photo of a freckled woman"
Killed: 9
```

**Comment by ronag** [comment]
I think I got it working with `pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`
