### ISSUE TITLE
Running 2.0 gives error

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#128]
```
/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: <8080486D-E510-3000-AA6A-F3AD49ACC172> /Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/image.so
  Expected in:     <8ADDD67A-2C07-3290-B140-DF1BD644AB8B> /Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/lib/libc10.dylib
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/Users/jimmygunawan/miniforge3/bin/imagine", line 5, in <module>
    from imaginairy.cmds import imagine_cmd
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/imaginairy/__init__.py", line 7, in <module>
    from .api import imagine, imagine_image_files  # noqa
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/imaginairy/api.py", line 16, in <module>
    from imaginairy.enhancers.clip_masking import get_img_mask
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/imaginairy/enhancers/clip_masking.py", line 8, in <module>
    from torchvision import transforms
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/quantization/mobilenetv2.py", line 6, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/ao/quantization/__init__.py)
```

**Comment by brycedrennan** [comment]
i dont think it works with conda

**Comment by enzyme69** [comment]
Thanks for info, somewhat with this macOS account I got conda in my base terminal. I open a new account and it works fine. Pretty strange indeed.
