### ISSUE TITLE
M1 8GB Memory Leak

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#131]
M1 8GB, was running a batch like 30 I set to repeat, after around 17, it just goes into complete halted and crashed. No more RAM left. I wonder if this is Apple's macOS bug?

```
    Image Generated. Timings: conditioning:3.59s sampling:324.59s safety-filter:3.46s total:333.45s
    🖼  [generated] saved to: ./outputs/generated/000058_97487418_kdpmpp2m15_PS7.5_portrait_of_a_wooden_puppet_with_big_eyes,_long_nose,_reading_book_at_sofar_[generated].jpg
Generating 🖼  16/30: "portrait of a wooden puppet with big eyes, long nose, reading book at sofar" 512x512px seed:644712797 prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [04:30<00:00, 18.06s/it]
    Image Generated. Timings: conditioning:2.85s sampling:271.05s safety-filter:3.72s total:279.41s
    🖼  [generated] saved to: ./outputs/generated/000059_644712797_kdpmpp2m15_PS7.5_portrait_of_a_wooden_puppet_with_big_eyes,_long_nose,_reading_book_at_sofar_[generated].jpg
Generating 🖼  17/30: "portrait of a wooden puppet with big eyes, long nose, reading book at sofar" 512x512px seed:443339967 prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m
 33%|██████████████████████████████████████▋                                                                             | 5/15 [01:54<03:48, 22.86s/it]
Traceback (most recent call last):
  File "/Users/blendersushi/miniconda3/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/cmds.py", line 266, in imagine_cmd
    imagine_image_files(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/api.py", line 75, in imagine_image_files
    for result in imagine(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/api.py", line 305, in imagine
    samples = sampler.sample(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/samplers/kdiff.py", line 120, in sample
    samples = self.sampler_func(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/vendored/k_diffusion/sampling.py", line 914, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/samplers/kdiff.py", line 248, in forward
    noise_pred = get_noise_prediction(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/samplers/base.py", line 81, in get_noise_prediction
    noise_pred_neutral, noise_pred_positive = denoise_func(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/samplers/kdiff.py", line 231, in _wrapper
    return self.inner_model(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/vendored/k_diffusion/external.py", line 130, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/vendored/k_diffusion/external.py", line 160, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/diffusion/ddpm.py", line 1200, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/diffusion/ddpm.py", line 1325, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/diffusion/openaimodel.py", line 841, in forward
    h = module(h, emb, context)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/diffusion/openaimodel.py", line 86, in forward
    x = layer(x, context)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/attention.py", line 441, in forward
    x = block(x, context=context[i])
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/attention.py", line 354, in forward
    return checkpoint_eval(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/diffusion/util.py", line 149, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/diffusion/util.py", line 162, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/attention.py", line 361, in _forward
    self.attn1(
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/attention.py", line 175, in forward
    return self.forward_splitmem(x, context=context, mask=mask)
  File "/Users/blendersushi/miniconda3/lib/python3.9/site-packages/imaginairy/modules/attention.py", line 232, in forward_splitmem
    raise RuntimeError(
RuntimeError: Not enough memory, use lower resolution (max approx. 384x384). Need: 0.0GB free, Have:0.0GB free

```

**Comment by brycedrennan** [comment]
I'm surprised you got it working at all in conda :-) 
I'm running it on 32gb m1 so not super comparable but after 30 images its not obvious that it's leaking memory. Using 23 GB though.

**Comment by enzyme69** [comment]
I usually use conda activate environment because I think I might have made environment from other repo, and it has all the requirements to run this imaginairy.

I don't know if that's the most efficient, but anyhow, imaginairy for python coder feels very user friendly.

**Comment by brycedrennan** [comment]
I didn't fix any memory leaks per-se but I think memory usage is improved in 7.1.1. - try it now

**Comment by brycedrennan** [comment]
Closing until I hear it's still broken.
