### ISSUE TITLE
Model SD-2.0-depth results in "invalid load key, '\xef'."

### ISSUE THREAD

**Issue by Marcel-Jan** [brycedrennan/imaginAIry#153]
Hi Bryce,

Thanks for all the work you do on imaginAIry. I use it a lot.

I've tried the --model SD-2.0-depth argument, but I get this error:
`Loading model /Users/marcel-jankrijgsman/.cache/huggingface/transformers/5e0d3f157ac24137dd4de7682509955274bf8788fe95bf1153692a26083419a9.f46826b774802b38764147be0d631cd4804e58ab6c338404a8bbb9e8eca375fb onto mps:0 backend...
Traceback (most recent call last):
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/cmds.py", line 288, in imagine_cmd
    imagine_image_files(
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/api.py", line 76, in imagine_image_files
    for result in imagine(
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/api.py", line 135, in imagine
    model = get_diffusion_model(
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/model_manager.py", line 130, in get_diffusion_model
    return _get_diffusion_model(
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/model_manager.py", line 189, in _get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/model_manager.py", line 52, in __getattr__
    model = load_model_from_config(
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/model_manager.py", line 105, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/utils.py", line 62, in instantiate_from_config
    return _cls(**params)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/modules/diffusion/ddpm.py", line 1614, in __init__
    self.depth_model = instantiate_from_config(depth_stage_config)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/utils.py", line 62, in instantiate_from_config
    return _cls(**params)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/modules/midas/api.py", line 166, in __init__
    model, _ = load_model(model_type)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/modules/midas/api.py", line 99, in load_model
    model = DPTDepthModel(
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/modules/midas/midas/dpt_depth.py", line 98, in __init__
    self.load(path)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/imaginairy/modules/midas/midas/base_model.py", line 16, in load
    parameters = torch.load(ckpt_path, map_location=torch.device("cpu"))
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/marcel-jankrijgsman/PythonProjects/stable-diffusion/venv/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xef'.`

Here is an example of one imagine command that resulted in this error:
`imagine "Napoleon on a robotic cyber horse" --model SD-2.1 --repeats 20 --fix-faces --steps 50 --outdir outputs/txt2img-samples/20230105_napoleon02`

I'm running this on a MacBook Pro with Apple M1 Max, Ventura 13.1, Python 3.10.7 and the latest version of imaginAIry.

**Comment by brycedrennan** [comment]
This looks like a model download was corrupted. I believe it outputs the path to the file before this error. Try deleting the file?

**Comment by brycedrennan** [comment]
Were you able to resolve this?

**Comment by Marcel-Jan** [comment]
I wasn't sure what file to delete. I've removed (backupped) model.ckpt and that seems to have solved it.
