### ISSUE TITLE
PyTorch breaks after update

### ISSUE THREAD

**Issue by order661015** [brycedrennan/imaginAIry#161]
First, thank you so much for your hard work on this.  This is the ONLY implementation of SD I can get to run properly on my Intel based Mac.

After the most recent updates, the following is seen:

Traceback (most recent call last):
  File "/Users/me/miniconda3/bin/imagine", line 5, in <module>
    from imaginairy.cmds import imagine_cmd
  File "/Users/me/miniconda3/lib/python3.9/site-packages/imaginairy/cmds.py", line 15, in <module>
    from imaginairy.train import train_diffusion_model
  File "/Users/me/miniconda3/lib/python3.9/site-packages/imaginairy/train.py", line 16, in <module>
    from pytorch_lightning.strategies import DDPStrategy
ModuleNotFoundError: No module named 'pytorch_lightning.strategies'

**Comment by brycedrennan** [comment]
will fix right now

**Comment by brycedrennan** [comment]
Fixed in 7.4.3

I'm surprised its working for you on intel and in conda - both of which I didn not intend to support.  Great though!
