### ISSUE TITLE
Pytorch-ROCm

### ISSUE THREAD

**Issue by kiufta** [brycedrennan/imaginAIry#174]
Dear Bryce,

I would like to know whether there are any barriers against using ROCm-pytorch?

**Comment by brycedrennan** [comment]
no idea. I hadn't heard of that till you mentioned it.  If you find some other version of stable diffusion working with ROCm I can look at what's involved.

**Comment by brycedrennan** [comment]
let me know if you try it out

**Comment by 414n** [comment]
I just did a test while using rocm-5.5.1. It seems like one needs to install a nightly version for compatibility with rocm (https://pytorch.org/get-started/locally/), but imaginairy doesn't seem to like it, currently:

```
$ pip install pipenv
$ pipenv install torch --index https://download.pytorch.org/whl/rocm5.4.2
$ imagine ...
✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory.

/some/path/imaginairy_venv/lib64/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libc10_cuda.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Received 1 prompt(s) and 0 input image(s). Will repeat the generations 1 times to create 1 images.
Traceback (most recent call last):
  File "/some/path/imaginairy_venv/bin/imagine", line 7, in <module>
    imaginairy.cli.imagine.imagine_cmd()
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/imaginairy/cli/imagine.py", line 144, in imagine_cmd
    return _imagine_cmd(
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/imaginairy/cli/shared.py", line 176, in _imagine_cmd
    filenames = imagine_image_files(
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/imaginairy/api.py", line 61, in imagine_image_files
    for result in imagine(
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/imaginairy/api.py", line 153, in imagine
    check_torch_version()
  File "/some/path/imaginairy_venv/lib64/python3.9/site-packages/imaginairy/utils/__init__.py", line 250, in check_torch_version
    raise RuntimeError("ImaginAIry is not compatible with torch>=2.0.0")
RuntimeError: ImaginAIry is not compatible with torch>=2.0.0
```

**Comment by brycedrennan** [comment]
Yes, the images produced when I installed torch 2.0.0 were garbage. I haven't had the time to debug it.
