### ISSUE TITLE
Can't download CKPT model

### ISSUE THREAD

**Issue by Explosion-Scratch** [brycedrennan/imaginAIry#182]
Getting this trace:
```
🤖🧠 imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
Generating 🖼  1/1: "A forest" 512x512px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art," seed:905663327 prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-diffusion-2-1-base/resolve/main/v2-1_512-ema-pruned.ckpt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/cmds.py", line 265, in imagine_cmd
    return _imagine_cmd(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/cmds.py", line 701, in _imagine_cmd
    imagine_image_files(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/api.py", line 84, in imagine_image_files
    for result in imagine(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/api.py", line 159, in imagine
    model = get_diffusion_model(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 145, in get_diffusion_model
    return _get_diffusion_model(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 203, in _get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 60, in __getattr__
    model = load_model_from_config(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 95, in load_model_from_config
    ckpt_path = get_cached_url_path(weights_location, category="weights")
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/model_manager.py", line 295, in get_cached_url_path
    r = requests.get(url)  # noqa
  File "/opt/homebrew/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-diffusion-2-1-base/resolve/main/v2-1_512-ema-pruned.ckpt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
```

**Comment by Explosion-Scratch** [comment]
Going to https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/v2-1_512-ema-pruned.ckpt tries to download the file (I cancelled it though)

**Comment by brycedrennan** [comment]
People who have reported similar issues were on corporate laptops with their own certificate issues.  Is python requests able to access *any* https site? I would expect not.   

As I believe this is not related to imaginairy I'm closing the issue.  Happy to re-open if we get more information though.

**Comment by Explosion-Scratch** [comment]
> People who have reported similar issues were on corporate laptops with their own certificate issues. Is python requests able to access _any_ https site? I would expect not.
> 
> As I believe this is not related to imaginairy I'm closing the issue. Happy to re-open if we get more information though.

Running personal MacBook M1 (base model) as Admin with no corporate restrictions 😕

**Comment by Explosion-Scratch** [comment]
![image](https://user-images.githubusercontent.com/61319150/213931277-00d9768e-26a5-4f15-87ba-ac6734461b17.png)
Seems to be connecting fine with speedtest-cli

**Comment by Explosion-Scratch** [comment]
Using the same version of python as earlier

**Comment by Explosion-Scratch** [comment]
I used to have AdGuard for Mac installed but I uninstalled it. I also removed its certificate in Keychain Access when I uninstalled it.

**Comment by brycedrennan** [comment]
see if `speedtest --secure` works

**Comment by Explosion-Scratch** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/61319150/213936394-92195e93-5b4c-41db-950f-d89540b95e2d.png">
Nope, what can I do to fix that though?

**Comment by brycedrennan** [comment]
seems to be a problem that pops up for mac users from time to time (based on my quick googling).  Some people said `pip install certifi` helped.  If that works for you I can at least have the library provide a better error message that suggests that. Let me know.

**Comment by Explosion-Scratch** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/61319150/213936809-b5c0d309-7e89-460f-b659-49b1b7e515bd.png">

Thanks for your help with this, did you want me to run any debug stuff? Stackoverflow says that this might fix the error

```python
httplib.HTTPSConnection(hostname, timeout=5, context=ssl._create_unverified_context())
```

**Comment by Explosion-Scratch** [comment]
Looks like I needed to run the Install Certificates.command file that comes with python, but it still didn't fix it for me. Regardless, I appreciate your help with this issue, using this project isn't a necessity for me so it doesn't really matter
