### ISSUE TITLE
OSError: openai/clip-vit-large-patch14 does not appear to have a file named pytorch_model.bin

### ISSUE THREAD

**Issue by alekrutkowski** [brycedrennan/imaginAIry#211]
```
Traceback (most recent call last):
  File "/home/alek/.local/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/cmds.py", line 265, in imagine_cmd
    return _imagine_cmd(
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/cmds.py", line 701, in _imagine_cmd
    imagine_image_files(
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/api.py", line 84, in imagine_image_files
    for result in imagine(
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/api.py", line 159, in imagine
    model = get_diffusion_model(
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/model_manager.py", line 144, in get_diffusion_model
    return _get_diffusion_model(
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/model_manager.py", line 202, in _get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/model_manager.py", line 59, in __getattr__
    model = load_model_from_config(
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/model_manager.py", line 123, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/utils.py", line 62, in instantiate_from_config
    return _cls(**params)
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/modules/diffusion/ddpm.py", line 770, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/modules/diffusion/ddpm.py", line 863, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/utils.py", line 62, in instantiate_from_config
    return _cls(**params)
  File "/home/alek/.local/lib/python3.8/site-packages/imaginairy/modules/clip_embedders.py", line 22, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "/home/alek/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2241, in from_pretrained
    raise EnvironmentError(
OSError: openai/clip-vit-large-patch14 does not appear to have a file named pytorch_model.bin but there is a file for TensorFlow weights. Use `from_tf=True` to load this model from those weights.
```

**Comment by alekrutkowski** [comment]
Running on WSL2/Ubuntu.

**Comment by brycedrennan** [comment]
That is strange. Try it again?

**Comment by brycedrennan** [comment]
Let me know if it still doesn't work.
