### ISSUE TITLE
Installation fail on M1 MacbookPro

### ISSUE THREAD

**Issue by JohnnyBDude** [brycedrennan/imaginAIry#223]
Hi! I came across your amazing software in latest HackerNewsLetter and i immediately knew i need to try that:)
I am having some issues with installation though.

As python is not my native language i am probably very bad at interpreting the error output.
I would love a hint at what could be wrong and what can i try to fix this.

What am i using:
* Macbook pro m1
* pip 22.3.1, python 3.10

What i have done:
1. Installed rust and setuptools-rust
2. pip install imaginairy

The error I get:

```
Collecting scipy
  Using cached scipy-1.10.0.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434
      Build dir: /private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434/.mesonpy-wqd4gyut/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C linker for the host machine: cc ld64 650.9
      C++ compiler for the host machine: c++ (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
      C++ linker for the host machine: c++ ld64 650.9
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      
      ../../meson.build:63:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
      The following exception(s) were encountered:
      Running `gfortran --version` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `gfortran -V` gave "[Errno 2] No such file or directory: 'gfortran'"
      Running `flang --version` gave "[Errno 2] No such file or directory: 'flang'"
      Running `flang -V` gave "[Errno 2] No such file or directory: 'flang'"
      Running `nvfortran --version` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `nvfortran -V` gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running `pgfortran --version` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `pgfortran -V` gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running `ifort --version` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifort -V` gave "[Errno 2] No such file or directory: 'ifort'"
      Running `ifx --version` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `ifx -V` gave "[Errno 2] No such file or directory: 'ifx'"
      Running `g95 --version` gave "[Errno 2] No such file or directory: 'g95'"
      Running `g95 -V` gave "[Errno 2] No such file or directory: 'g95'"
      
      A full log can be found at /private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434/.mesonpy-wqd4gyut/build/meson-logs/meson-log.txt
      + meson setup --prefix=/Users/johnnyb/.pyenv/versions/3.10.1 /private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434 /private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434/.mesonpy-wqd4gyut/build --native-file=/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      Traceback (most recent call last):
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 1060, in build_wheel
          with _project(config_settings) as project:
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 975, in _project
          with Project.with_temp_working_dir(
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 750, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 632, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 680, in _configure
          self._meson('setup', *setup_args)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-build-env-n2z1064x/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/Users/johnnyb/.pyenv/versions/3.10.1/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--prefix=/Users/johnnyb/.pyenv/versions/3.10.1', '/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434', '/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434/.mesonpy-wqd4gyut/build', '--native-file=/private/var/folders/kg/1ls2mzls1_j0j4102rcycx780000gn/T/pip-install-43mr0mc6/scipy_eda8ed82777a471d96d023abb0d83434/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Bless all forms of intelligence

**Comment by brycedrennan** [comment]
just a guess but try installing an older version of scipy. Maybe 1.9.3 https://pypi.org/project/scipy/1.9.3/#history

**Comment by brycedrennan** [comment]
`pip install scipy==1.9.3`
`pip install imaginairy`

**Comment by brycedrennan** [comment]
Let me know if that worked.

**Comment by JohnnyBDude** [comment]
Thanks for a hint.
That did not work, but i was able to find a solution - there were some missing scipy dependencies.

Steps I used:
```
brew install gcc # Installing compilers got me to another error
brew install openblas # Another scipy system dependency

# Setting shell variables as advised by openblas installer proved necessary
export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig"
```
