### ISSUE TITLE
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'

### ISSUE THREAD

**Issue by cartland** [brycedrennan/imaginAIry#294]
I ran into an error with one of the dependencies and found a workaround on Reddit. One of the dependencies might be broken.

# Error
```bash
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'
```

# Workaround
https://www.reddit.com/r/StableDiffusion/comments/115fmc9/cannot_import_name_safe_weights_name_from/
```bash
>> pip install diffusers==0.12.1
```

# Current project is using diffusers==0.14.0
This project is currently using diffusers 0.14.0, which appears to be the version that does not work for me.
https://github.com/brycedrennan/imaginAIry/blob/3012d28357eb53c5b65200ccb49a25691bb97d16/requirements-dev.txt#L46

# Additional Details
```bash
>> brew install pyenv
>> pyenv install 3.10.10
>> pyenv global 3.10.10
>> pip install imaginairy
>> pip show imaginairy
Name: imaginAIry
Version: 5.0.1
Summary: AI imagined images. Pythonic generation of stable diffusion images.
Home-page: UNKNOWN
Author: Bryce Drennan
Author-email: 
License: UNKNOWN
Location: /Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages
Requires: click, click-shell, diffusers, einops, fairscale, ftfy, gfpgan, imageio, kornia, numpy, omegaconf, Pillow, protobuf, psutil, pytorch-lightning, realesrgan, timm, torch, torchdiffeq, torchmetrics, torchvision, tqdm, transformers
Required-by: 

# Add to ~/.zshrc
export PATH="$PATH:$HOME/.pyenv/versions/3.10.10/bin"

>> imagine
Traceback (most recent call last):
  File "/Users/cartland/.pyenv/versions/3.10.10/bin/imagine", line 5, in <module>
    from imaginairy.cmds import imagine_cmd
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/imaginairy/__init__.py", line 7, in <module>
    from .api import imagine, imagine_image_files  # noqa
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/imaginairy/api.py", line 25, in <module>
    from imaginairy.safety import SafetyMode, create_safety_score
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/imaginairy/safety.py", line 5, in <module>
    from diffusers.pipelines.stable_diffusion import safety_checker as safety_checker_mod
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/__init__.py", line 55, in <module>
    from .pipelines import (
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 64, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/Users/cartland/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/utils/__init__.py)

>> pip install diffusers==0.12.1
>> imagine "a scenic landscape" "a photo of a dog" "photo of a fruit bowl" "portrait photo of a freckled woman" "a bluejay"
# [Command executes successfully]
```

**Comment by brycedrennan** [comment]
Thanks for the report, I'll dig in.

**Comment by brycedrennan** [comment]
I was unable to reproduce. I suspect the issue no longer applies.
