### ISSUE TITLE
Fail to describe on Mac M1

### ISSUE THREAD

**Issue by zmactep** [brycedrennan/imaginAIry#302]
I am trying to describe a sample image of a bird from README with `aimg describe` and see the following error:
```
% aimg describe source.jpg
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/bin/aimg", line 6, in <module>
    imaginairy.cli.main.aimg()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/cli/describe.py", line 24, in describe_cmd
    print(generate_caption(img.copy()))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/enhancers/describe_image_blip.py", line 59, in generate_caption
    caption = blip_model().generate(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/blip.py", line 198, in generate
    outputs = self.text_decoder.generate(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/transformers/generation/utils.py", line 1490, in generate
    return self.beam_search(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/transformers/generation/utils.py", line 2749, in beam_search
    outputs = self(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/med.py", line 986, in forward
    outputs = self.bert(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/med.py", line 879, in forward
    encoder_outputs = self.encoder(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/med.py", line 499, in forward
    layer_outputs = layer_module(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/med.py", line 407, in forward
    cross_attention_outputs = self.crossattention(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/med.py", line 315, in forward
    self_outputs = self.self(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/imagine/lib/python3.10/site-packages/imaginairy/vendored/blip/med.py", line 188, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0
```

<details> 
  <summary>My installation</summary>

```
% conda list
# packages in environment at /opt/homebrew/Caskroom/miniconda/base/envs/imagine:
#
# Name                    Version                   Build  Channel
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2023.01.10           hca03da5_0  
certifi                   2022.12.7       py310hca03da5_0  
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
click-help-colors         0.9.1                    pypi_0    pypi
click-shell               2.1                      pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
diffusers                 0.14.0                   pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
facexlib                  0.2.5                    pypi_0    pypi
fairscale                 0.4.13                   pypi_0    pypi
filelock                  3.10.6                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fonttools                 4.39.2                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.3.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
huggingface-hub           0.13.3                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.27.0                   pypi_0    pypi
imaginairy                11.1.0                   pypi_0    pypi
importlib-metadata        6.1.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kornia                    0.6.10                   pypi_0    pypi
libffi                    3.4.2                hca03da5_6  
lightning-utilities       0.8.0                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h313beb8_0  
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
open-clip-torch           2.16.0                   pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h1a28f6b_0  
packaging                 23.0                     pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1          py310hca03da5_0  
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.10.10              hc0d8a6c_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-lightning         1.9.4                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
safetensors               0.3.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                65.6.3          py310hca03da5_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.1               h80987f9_0  
timm                      0.6.13                   pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
tokenizers                0.13.2                   pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.27.3                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2022g                h04d1e81_0  
urllib3                   1.26.15                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
wheel                     0.38.4          py310hca03da5_0  
xz                        5.2.10               h80987f9_1  
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5a0b063_0  
```

```
% pip freeze
aiohttp==3.8.4
aiosignal==1.3.1
antlr4-python3-runtime==4.9.3
async-timeout==4.0.2
attrs==22.2.0
certifi @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_5d968ni_yn/croot/certifi_1671487774636/work/certifi
charset-normalizer==3.1.0
click==8.1.3
click-help-colors==0.9.1
click-shell==2.1
contourpy==1.0.7
cycler==0.11.0
diffusers==0.14.0
einops==0.6.0
facexlib==0.2.5
fairscale==0.4.13
filelock==3.10.6
filterpy==1.4.5
fonttools==4.39.2
frozenlist==1.3.3
fsspec==2023.3.0
ftfy==6.1.1
huggingface-hub==0.13.3
idna==3.4
imageio==2.27.0
imaginAIry==11.1.0
importlib-metadata==6.1.0
kiwisolver==1.4.4
kornia==0.6.10
lightning-utilities==0.8.0
llvmlite==0.39.1
matplotlib==3.7.1
multidict==6.0.4
numba==0.56.4
numpy==1.23.5
omegaconf==2.3.0
open-clip-torch==2.16.0
opencv-python==4.7.0.72
packaging==23.0
Pillow==9.4.0
protobuf==3.20.3
psutil==5.9.4
pyparsing==3.0.9
python-dateutil==2.8.2
pytorch-lightning==1.9.4
PyYAML==6.0
regex==2023.3.23
requests==2.28.2
safetensors==0.3.0
scipy==1.10.1
sentencepiece==0.1.97
six==1.16.0
timm==0.6.13
tokenizers==0.13.2
torch==1.13.1
torchdiffeq==0.2.3
torchmetrics==0.11.4
torchvision==0.14.1
tqdm==4.65.0
transformers==4.27.3
typing_extensions==4.5.0
urllib3==1.26.15
wcwidth==0.2.6
yarl==1.8.2
zipp==3.15.0
```

</details>

**Comment by Cristobalpixel** [comment]
Same here on M1 Pro.

**Comment by KixPanganiban** [comment]
Same on M2 Pro
