### ISSUE TITLE
ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub'

### ISSUE THREAD

**Issue by christopherafbjur** [brycedrennan/imaginAIry#329]
Hi! Just installed this library and tried to run it without success. Any ideas what might be causing this? Thanks in advance!

**Stacktrace:**

```
imagine "a scenic landscape"
✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory.

Received 1 prompt(s) and 0 input image(s). Will repeat the generations 1 times to create 1 images.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/imagine", line 7, in <module>
    imaginairy.cli.imagine.imagine_cmd()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imaginairy/cli/imagine.py", line 97, in imagine_cmd
    return _imagine_cmd(
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imaginairy/cli/shared.py", line 136, in _imagine_cmd
    prompt = ImaginePrompt(
             ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imaginairy/schema.py", line 156, in __init__
    self.validate()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imaginairy/schema.py", line 226, in validate
    from imaginairy.model_manager import get_model_default_image_size
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imaginairy/model_manager.py", line 15, in <module>
    from transformers.utils.hub import HfFolder
ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/hub.py)
```

**Transformers version:**
4.29.2

**Output running "aimg system-info":**
```
imaginairy_version:            11.0.0
imaginairy_path:               /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/imaginairy
python_version:                3.11.3
python_installation_path:      /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
device:                        mps:0
torch_version:                 2.0.1
platform:                      darwin
hardware_description:          macOS-13.3.1-arm64-arm-64bit
ram_gb:                        16.0
graphics_card:                 Apple MPS
```

**Comment by brycedrennan** [comment]
It's not compatible with torch 2.0. This comes up enough that maybe I should add a specific error message for it.

**Comment by christopherafbjur** [comment]
> Downgrading to python 3.9.1 solved it for me.

Thanks this worked for me @IDDT

**Comment by christopherafbjur** [comment]
> It's not compatible with torch 2.0. This comes up enough that maybe I should add a specific error message for it.

Yes @brycedrennan that might be a good idea. Not sure how clear this is for python users with more experience than me. In my case I have very little experience with Python and downloaded the latest version just to try this lib. So it's unclear to me why dependencies are installed by this lib that aren't supported? Or maybe it's just something that come with Python based on your version?

**Comment by brycedrennan** [comment]
The theory would be that you installed torch before installing my library. Otherwise it should have automatically installed the proper version. not sure if that's what's happening though
