### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0

### ISSUE THREAD

**Issue by imitatorgkw** [brycedrennan/imaginAIry#348]
I tried the command imagine --control-image dog.jpg --control-mode hed "photo of a dalmation" but I got an error: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! How can I fix this?

**Comment by pablodavila95** [comment]
I'm having the same issue. Could you find a fix?

**Comment by brycedrennan** [comment]
Do you still have this problem on just release `13.2.0`.  If so can you provide the output of `aimg system-info` as well?

**Comment by malreynold** [comment]
Hi there I've just installed Imaginairy and having this issue and protected name space and also some "triton" module missing... when launching a colorize command maybe this helps: 

/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_config_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting \`model_config['protected_namespaces'] = ()\`.
  warnings.warn(
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'

**And after loading models** : 
`Traceback (most recent call last):
  File "/home/simerron/.pyenv/versions/3.10.13/bin/aimg", line 6, in <module>
    imaginairy.cli.main.aimg()
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/cli/colorize.py", line 61, in colorize_cmd
    img = colorize_img(img, caption=caption)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/colorize.py", line 39, in colorize_img
    result = list(imagine(prompt))[0]
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/api.py", line 176, in imagine
    result = _generate_single_image(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/api.py", line 547, in _generate_single_image
    samples = sampler.sample(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/samplers/kdiff.py", line 135, in sample
    samples = self.sampler_func(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/vendored/k_diffusion/sampling.py", line 929, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/samplers/kdiff.py", line 263, in forward
    noise_pred = get_noise_prediction(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/samplers/base.py", line 81, in get_noise_prediction
    noise_pred_neutral, noise_pred_positive = denoise_func(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/samplers/kdiff.py", line 246, in _wrapper
    return self.inner_model(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/vendored/k_diffusion/external.py", line 130, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/vendored/k_diffusion/external.py", line 160, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/modules/cldm.py", line 414, in apply_model
    eps = diffusion_model(
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy/modules/cldm.py", line 36, in forward
    emb = self.time_embed(t_emb)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)`

**Output of system-info** : 
/home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_config_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
imaginairy_version:            13.2.0
imaginairy_path:               /home/simerron/.pyenv/versions/3.10.13/lib/python3.10/site-packages/imaginairy
python_version:                3.10.13
python_installation_path:      /home/simerron/.pyenv/versions/3.10.13/bin/python3.10
device:                        cuda
torch_version:                 1.13.1+cu117
platform:                      linux
hardware_description:          Linux-6.1.53-1-MANJARO-x86_64-with-glibc2.38-NVIDIA GeForce RTX 2080 SUPER
ram_gb:                        31.27
cuda_version:                  11.7
graphics_card:                 NVIDIA GeForce RTX 2080 SUPER
graphics_card_memory:          8353153024
graphics_card_processor_count: 48
graphics_card_hw_version:      7.5

**Comment by brycedrennan** [comment]
This is happening in deprecated code after the rewrite. The beta version should no longer be affected.
