### ISSUE TITLE
ISSUE importing imaginary - numpy version

### ISSUE THREAD

**Issue by enzyme69** [brycedrennan/imaginAIry#35]
```
>>> import imaginairy
/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: <8080486D-E510-3000-AA6A-F3AD49ACC172> /Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/image.so
  Expected in:     <8ADDD67A-2C07-3290-B140-DF1BD644AB8B> /Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/lib/libc10.dylib
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/imaginairy/__init__.py", line 7, in <module>
    from .api import imagine, imagine_image_files  # noqa
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/imaginairy/api.py", line 16, in <module>
    from imaginairy.enhancers.clip_masking import get_img_mask
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/imaginairy/enhancers/clip_masking.py", line 8, in <module>
    from torchvision import transforms
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/__init__.py", line 7, in <module>
    from torchvision import models
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/__init__.py", line 18, in <module>
    from . import quantization
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torchvision/models/quantization/mobilenetv2.py", line 6, in <module>
    from torch.ao.quantization import QuantStub, DeQuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' (/Users/jimmygunawan/miniforge3/lib/python3.9/site-packages/torch/ao/quantization/__init__.py)

```

And during the pip installation of ImaginAIry it complains:
  ```
ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
(base) jimmygunawan@192-168-1-114 ~ % pip3 install numpy
Collecting numpy
  Using cached numpy-1.23.3-cp39-cp39-macosx_11_0_arm64.whl (13.4 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-macos 2.6.0 requires numpy~=1.19.2, but you have numpy 1.23.3 which is incompatible.
scipy 1.7.1 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.3 which is incompatible.
```

**Comment by enzyme69** [comment]
I tried a different login account and reinstall using pip3, still many errors:

`  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-p5pkoryp/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-p5pkoryp/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-p5pkoryp/normal'
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-p5pkoryp/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-p5pkoryp/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-p5pkoryp/overlay'
`

 ```
WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/normal/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/normal'
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/overlay/lib/python3.9/site-packages
  sysconfig: /Library/Python/3.9/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/overlay'
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/tmpf4ls5epu
       cwd: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/tokenizers_faca50ef31204c37b203b2ba02582246
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 2, in <module>
      from setuptools_rust import Binding, RustExtension
    File "/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/overlay/lib/python3.9/site-packages/setuptools_rust/__init__.py", line 1, in <module>
      from .build import build_rust
    File "/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-build-env-l128lq7n/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 23, in <module>
      from setuptools.command.build import build as CommandBuild  # type: ignore[import]
  ModuleNotFoundError: No module named 'setuptools.command.build'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/12/57/da0cb8e40437f88630769164a66afec8af294ff686661497b6c88bc08556/tokenizers-0.12.1.tar.gz#sha256=070746f86efa6c873db341e55cf17bb5e7bdd5450330ca8eca542f5c3dab2c66 (from https://pypi.org/simple/tokenizers/). Command errored out with exit status 1: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/tmpf4ls5epu Check the logs for full command output.

```

```
ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/setup.py'"'"'; __file__='"'"'/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-wheel-z0ru1_84
       cwd: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/
  Complete output (27 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/setup.py", line 147, in <module>
      setup(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/.eggs/torch-1.12.1-py3.9-macosx-10.9-universal2.egg'
  ----------------------------------------
  ERROR: Failed building wheel for basicsr
  Running setup.py clean for basicsr
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/setup.py'"'"'; __file__='"'"'/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7
  Complete output (27 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/setup.py", line 147, in <module>
      setup(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 806, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
      dist = best[req.key] = env.best_match(
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
      return self.obtain(req, installer)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
      return installer(requirement)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py", line 877, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
      wheel.install_as_egg(dist_location)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 95, in install_as_egg
      self._install_as_egg(destination_eggdir, zf)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
      self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
    File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
      os.mkdir(destination_eggdir)
  FileExistsError: [Errno 17] File exists: '/private/var/folders/sc/60t303_n5ysgp00p2d7gg6p80000gq/T/pip-install-_ae40vfu/basicsr_c7d13ff9e29f4b0997198076ce38a3f7/.eggs/torch-1.12.1-py3.9-macosx-10.9-universal2.egg'
  ----------------------------------------
  ERROR: Failed cleaning build dir for basicsr

```

**Comment by enzyme69** [comment]
Okey, I think my issue is not using environment, and it was messy. But in the end I was following this steps here:
https://weirdwonderfulai.art/resources/running-stable-diffusion-on-m1-m2-mac/

And then installing imaginAIry and manage to have it running without issue within Python environment. 

The issue now is that it's running super slow at M1 8GB, but I want to open a new issue.
