### ISSUE TITLE
Not Working on Mac - ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' (/opt/homebrew/lib/python3.11/site-packages/transformers/utils/hub.py)

### ISSUE THREAD

**Issue by aleksfadini** [brycedrennan/imaginAIry#352]
```
❯ imagine "a scenic landscape"                                                                                                  15:06:04
✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory.

Received 1 prompt(s) and 0 input image(s). Will repeat the generations 1 times to create 1 images.
Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 7, in <module>
    imaginairy.cli.imagine.imagine_cmd()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/cli/imagine.py", line 97, in imagine_cmd
    return _imagine_cmd(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/cli/shared.py", line 136, in _imagine_cmd
    prompt = ImaginePrompt(
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/schema.py", line 156, in __init__
    self.validate()
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/schema.py", line 226, in validate
    from imaginairy.model_manager import get_model_default_image_size
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/model_manager.py", line 15, in <module>
    from transformers.utils.hub import HfFolder
ImportError: cannot import name 'HfFolder' from 'transformers.utils.hub' (/opt/homebrew/lib/python3.11/site-packages/transformers/utils/hub.py)
```

aimg system-info:
```

 ❯ aimg system-info                                                                                                                 15:06:14
imaginairy_version:            11.0.0
imaginairy_path:               /opt/homebrew/lib/python3.11/site-packages/imaginairy
python_version:                3.11.4
python_installation_path:      /opt/homebrew/opt/python@3.11/bin/python3.11
device:                        mps:0
torch_version:                 2.0.1
platform:                      darwin
hardware_description:          macOS-13.4.1-arm64-arm-64bit
ram_gb:                        16.0
graphics_card:                 Apple MPS
```

**Comment by pantinx** [comment]
Hello, I got same issue on Windows. Did you manage to resolve it ?

**Comment by brycedrennan** [comment]
Python 3.11 is not supported. I'm surprised you were able to get it installed at all. 

If you continue to encounter this problem on python 3.10 let me know and I'll re-open the issue.
