### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by reubenfirmin** [brycedrennan/imaginAIry#366]
```
virtualenv env
env/bin/pip install imaginairy

....


INFO: pip is looking at multiple versions of imageio to determine which version is compatible with other requirements. This could take a while.
Collecting imageio>=2.9.0
  Downloading imageio-2.31.2-py3-none-any.whl (313 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.2/313.2 kB 1.7 MB/s eta 0:00:00
  Downloading imageio-2.31.1-py3-none-any.whl (313 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.2/313.2 kB 477.8 kB/s eta 0:00:00
INFO: pip is looking at multiple versions of imageio to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
ERROR: Exception:
Traceback (most recent call last):
  File "/expanse/imagine/env/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/expanse/imagine/env/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/expanse/imagine/env/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/expanse/imagine/env/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/expanse/imagine/env/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/expanse/imagine/env/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

**Comment by brycedrennan** [comment]
Python 3.11 is not supported

**Comment by reubenfirmin** [comment]
It was released 10 months ago and is default on many distros at this point. When will you support it?

**Comment by brycedrennan** [comment]
pull requests welcome. supporting 3.11 means switching to torch 2.0, which broke things last time I tried to port over
