### ISSUE TITLE
aimg colorize RuntimeError

### ISSUE THREAD

**Issue by McFalljb** [brycedrennan/imaginAIry#375]
Running aimg colorize I first received an error about triton not being installed

```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
  0%|      
```

This was easy enough to solve by pip installing triton

but I also run into the issue below

```
➜  workspace aimg colorize home.jpeg         
  0%|                                                                                                              | 0/1 [00:00<?, ?it/s]Colorizing home.jpeg and saving it to ./outputs/colorized/000001_home.jpeg
two people kissing and having fun on the street
mode='colorize' image=<LazyLoadingImage filepath=home.jpeg url=None> image_raw=None strength=2
🖼  Generating  1/1: "two people kissing and having fun on the street. color photo, sharp-focus, highly detailed, intricate, Canon 5D" 1000x1024px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art," seed:None prompt-strength:12.0 steps:30 sampler-type:k_dpmpp_2m init-image-strength:0.0 model:SD-1.5
mode='colorize' image=<LazyLoadingImage filepath=home.jpeg url=None> image_raw=None strength=2
Loading model /home/mcfaljb/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/889b629140e71758e1e0006e355c331a5744b4bf/v1-5-pruned-emaonly.ckpt onto cuda backend...
                                                                                                                                            Loading model /home/mcfaljb/.cache/huggingface/hub/models--ioclab--ioc-controlnet/snapshots/87b589ef8aa80c37be814fffc31203853a2928c1/models/control_v1p_sd15_brightness.safetensors onto cuda backend...
  0%|                                                                                                             | 0/29 [00:03<?, ?it/s]
  0%|                                                                                                              | 0/1 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "/home/mcfaljb/.local/bin/aimg", line 6, in <module>
    imaginairy.cli.main.aimg()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/cli/colorize.py", line 61, in colorize_cmd
    img = colorize_img(img, caption=caption)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/colorize.py", line 39, in colorize_img
    result = list(imagine(prompt))[0]
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/api.py", line 176, in imagine
    result = _generate_single_image(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/api.py", line 547, in _generate_single_image
    samples = sampler.sample(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/samplers/kdiff.py", line 135, in sample
    samples = self.sampler_func(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/vendored/k_diffusion/sampling.py", line 929, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/samplers/kdiff.py", line 263, in forward
    noise_pred = get_noise_prediction(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/samplers/base.py", line 81, in get_noise_prediction
    noise_pred_neutral, noise_pred_positive = denoise_func(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/samplers/kdiff.py", line 246, in _wrapper
    return self.inner_model(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/vendored/k_diffusion/external.py", line 130, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/vendored/k_diffusion/external.py", line 160, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/modules/cldm.py", line 414, in apply_model
    eps = diffusion_model(
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy/modules/cldm.py", line 36, in forward
    emb = self.time_embed(t_emb)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mcfaljb/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)
```

Thank you for your time

**Comment by brycedrennan** [comment]
Thanks for reporting these issues.  Can you please paste the output of 
`aimg system-info` so I can understand what kind of environment you're running in?

**Comment by McFalljb** [comment]
```
imaginairy_version:            13.1.0
imaginairy_path:               /home/mcfaljb/.local/lib/python3.10/site-packages/imaginairy
python_version:                3.10.12
python_installation_path:      /usr/bin/python3
device:                        cuda
torch_version:                 1.13.1+cu117
platform:                      linux
hardware_description:          Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35-NVIDIA GeForce GTX 1080
ram_gb:                        62.73
cuda_version:                  11.7
graphics_card:                 NVIDIA GeForce GTX 1080
graphics_card_memory:          8484618240
graphics_card_processor_count: 20
graphics_card_hw_version:      6.1
```

**Comment by brycedrennan** [comment]
Well nothing obviously wrong. The command works for me. Must be specific to the graphics card.  I'm don't really have a way of debugging this.

**Comment by McFalljb** [comment]
I understand, I guess my only question would with this part of the error

`Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_addmm)`

Would there be anyway to specify a "device" instead of leaving it up to the program to figure out?
I tried looking though the code for somewhere in colorize to add this functionality with no luck so far.

**Comment by brycedrennan** [comment]
Sorry for the so-late-you-certainly-dont-care-anymore response.  I wish I could debug this, definitely a bug.  

That being said the library is now rewritten and this bug is in the old code.
