### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by thanu-sumith** [brycedrennan/imaginAIry#377]
cannot import name 'HfFolder' from 'transformers.utils.hub'

**Comment by brycedrennan** [comment]
Please copy the results of `aimg system-info` so I can know what environment you're running in.

**Comment by brycedrennan** [comment]
Will open if we get more information.

**Comment by lnittman** [comment]
i'm running into this as well - 

```
$ aimg system-info
imaginairy_version: 11.0.0
imaginairy_path: /opt/homebrew/lib/python3.11/site-packages/imaginairy
python_version: 3.11.4
python_installation_path: /opt/homebrew/opt/python@3.11/bin/python3.11
device:  mps:0
torch_version: 2.0.1
platform: darwin
hardware_description: macOS-14.0-arm64-arm-64bit
ram_gb: 64.0
graphics_card: Apple MPS
```

```
aimg edit ~/Downloads/hn.jpg -p "subtle album artwork variation, distortion, crushed"
✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory.

Received 1 prompt(s) and 1 input image(s). Will repeat the generations 1 times to create 1 images.
Traceback (most recent call last):
  File "/opt/homebrew/bin/aimg", line 6, in <module>
    imaginairy.cli.main.aimg()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/cli/edit.py", line 98, in edit_cmd
    return _imagine_cmd(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/cli/shared.py", line 136, in _imagine_cmd
    prompt = ImaginePrompt(
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/schema.py", line 156, in __init__
    self.validate()
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/schema.py", line 177, in validate
    self.init_image = LazyLoadingImage(filepath=self.init_image)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/imaginairy/schema.py", line 26, in __init__
    raise FileNotFoundError(f"File does not exist: {filepath}")
FileNotFoundError: File does not exist: /Users/nit/Downloads/hn.jpg
```

**Comment by lnittman** [comment]
seems fixed if I update the HfFolder import in imaginairy/model_manager.py:15

`from transformers.utils.hub import HfFolder`

->

`from huggingface_hub import HfFolder`
