### ISSUE TITLE
Prompt Based Masking error - ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by ChristopherDaigle** [brycedrennan/imaginAIry#381]
Issue with SSL certificate

<details><summary>Larger log:</summary>

```shell
imagine \
    --init-image patio_images/zlow_scrn.png \
    --mask-prompt "house AND NOT (deck){*6}" \
    --mask-mode replace \
    --mask-modify-original \
    --init-image-strength .1 \
    "a patio with a gazebo, firepit, and outdoor kitchen in a natural form"


    (venv_patio) (base) A_USER@A_MACHINE patio_gen % imagine \ 
        --init-image patio_images/zlow_scrn.png \
        --mask-prompt "house AND NOT (deck){*6}" \
        --mask-mode replace \
        --mask-modify-original \
        --init-image-strength .1 \
        "a patio with a gazebo, firepit, and outdoor kitchen in a natural form"
    A_PATH/lib/python3.10/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_config_path" has conflict with protected namespace "model_".

    You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
      warnings.warn(
    ✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory.

    Received 1 prompt(s) and 1 input image(s). Will repeat the generations 1 times to create 1 images.
    🖼  Generating  1/1: "a patio with a gazebo, firepit, and outdoor kitchen in a natural form" 512x512px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art," seed:None prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m init-image-strength:0.1 model:SD-1.5
    Loading model /Users/christopherdaigle/.cache/huggingface/hub/models--julienacquaviva--inpainting/snapshots/2155ff7fe38b55f4c0d99c2f1ab9b561f8311ca7/sd-v1-5-inpainting.ckpt onto mps:0 backend...
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
        self.send(msg)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
        self.connect()
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
        return self.sslsocket_class._create(
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
        self.do_handshake()
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "A_PATH/bin/imagine", line 7, in <module>
        imaginairy.cli.imagine.imagine_cmd()
      File "A_PATH/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
      File "A_PATH/lib/python3.10/site-packages/click/core.py", line 1078, in main
        rv = self.invoke(ctx)
      File "A_PATH/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "A_PATH/lib/python3.10/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
      File "A_PATH/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "A_PATH/lib/python3.10/site-packages/imaginairy/cli/imagine.py", line 144, in imagine_cmd
        return _imagine_cmd(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/cli/shared.py", line 181, in _imagine_cmd
        filenames = imagine_image_files(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/api.py", line 61, in imagine_image_files
        for result in imagine(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/api.py", line 176, in imagine
        result = _generate_single_image(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/api.py", line 335, in _generate_single_image
        mask_image, mask_grayscale = get_img_mask(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/enhancers/clip_masking.py", line 46, in get_img_mask
        mask_cache = get_img_masks(img, descriptions)
      File "A_PATH/lib/python3.10/site-packages/imaginairy/enhancers/clip_masking.py", line 92, in get_img_masks
        preds = clip_mask_model()(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/enhancers/clip_masking.py", line 21, in clip_mask_model
        model = CLIPDensePredT(version="ViT-B/16", reduce_dim=64, complex_trans_conv=True)
      File "A_PATH/lib/python3.10/site-packages/imaginairy/vendored/clipseg/__init__.py", line 417, in __init__
        super().__init__(version, reduce_cond, reduce_dim, prompt, n_tokens)
      File "A_PATH/lib/python3.10/site-packages/imaginairy/vendored/clipseg/__init__.py", line 145, in __init__
        self.clip_model, _ = clip.load(version, device="cpu", jit=False)
      File "A_PATH/lib/python3.10/site-packages/imaginairy/vendored/clip/clip.py", line 147, in load
        model_path = _download(
      File "A_PATH/lib/python3.10/site-packages/imaginairy/vendored/clip/clip.py", line 65, in _download
        with urllib.request.urlopen(url) as source, open(download_target, "wb") as output:
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
        response = self._open(req, data)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
        result = func(*args)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

</details>

**Comment by brycedrennan** [comment]
Every time we've looked into certificate issues like this it was something about the environment and not really related to imaginairy. Can have to do with VPN setup or corporate managed laptos.

**Comment by ChristopherDaigle** [comment]
@brycedrennan , I'll upgrade my version now that it's been updated for the arguments and give it a shot, but I'm using this package on a personal machine, MacBook Pro, on a regular internet connection (hobby work, not business 🙂 )

**Comment by ChristopherDaigle** [comment]
@brycedrennan with the latest update, this works for me now as well!
