### ISSUE TITLE
Erros in Python3.10 Venv Environment

### ISSUE THREAD

**Issue by 5l1v3r1** [brycedrennan/imaginAIry#402]
-For imagine function it throws this error : 

Loading weights from C:\imaginAIry\venv\lib\site-packages\imaginairy\.cached-aimg\weights\v1-5-pruned-emaonly.ckpt
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\imaginAIry\venv\Scripts\imagine.exe\__main__.py", line 7, in <module>
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\imaginAIry\venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\cli\imagine.py", line 144, in imagine_cmd
    return _imagine_cmd(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\cli\shared.py", line 177, in _imagine_cmd
    filenames = imagine_image_files(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\api.py", line 61, in imagine_image_files
    for result in imagine(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\api.py", line 177, in imagine
    result = _generate_single_image(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\api_refiners.py", line 74, in _generate_single_image
    sd = get_diffusion_model_refiners(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\model_manager.py", line 251, in get_diffusion_model_refiners
    return _get_diffusion_model_refiners(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\model_manager.py", line 291, in _get_diffusion_model_refiners
    sd = _get_diffusion_model_refiners_only(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\model_manager.py", line 350, in _get_diffusion_model_refiners_only
    ) = load_stable_diffusion_compvis_weights(weights_location)
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\model_manager.py", line 729, in load_stable_diffusion_compvis_weights
    text_encoder_state_dict = cast_weights(
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\weight_management\conversion.py", line 113, in cast_weights
    return weight_map.cast_weights(source_weights)
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\weight_management\conversion.py", line 77, in cast_weights
    source_prefix = self.source_aliases.get(source_prefix, source_prefix)
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\weight_management\conversion.py", line 50, in source_aliases
    return self._mapping_info.get("source_aliases", {})
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\weight_management\conversion.py", line 40, in _mapping_info
    with open(self.filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\imaginAIry\\venv\\Lib\\site-packages\\imaginairy\\weight_management\\maps\\stable-diffusion-1-5_text_compvis_TO_diffusers.json'

-for aimg server it throws this error 

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\imaginAIry\venv\Scripts\aimg.exe\__main__.py", line 7, in <module>
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\imaginAIry\venv\lib\site-packages\click_shell\core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\imaginAIry\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\cli\run_api.py", line 13, in run_server_cmd
    from imaginairy.http_app.app import app
  File "C:\imaginAIry\venv\lib\site-packages\imaginairy\http_app\app.py", line 66, in <module>
    app.mount("/", StaticFiles(directory=static_folder, html=True), name="static")
  File "C:\imaginAIry\venv\lib\site-packages\starlette\staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'C:\imaginAIry\venv\lib\site-packages\imaginairy\http_app/stablestudio/dist' does not exist

**Comment by brycedrennan** [comment]
Thanks for the report. I'll double check some things on my end.

**Comment by brycedrennan** [comment]
Yep things broken on my end.

**Comment by brycedrennan** [comment]
Thanks for bringing that to my attention those were some serious bugs. I've just release `imaginairy==14.0.0b4` which addresses those issues
