### ISSUE TITLE
control mode details

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#469]
Called like this:

imagine --upscale  --init-image /root/1.jpg --init-image-strength "$init_image_strength" --repeats 5 --steps 80 --size 1200x768  --control-image /root/1.jpg --control-mode details --model SD-1.5 "a horse"

  size:1200x768px-(25:16) seed:292254896 prompt-strength:7.5 steps:80 solver-type:ddim init-image-strength:0.39 arch:sd15 weights:sd15
    Loading model /root/.cache/huggingface/hub/models--lllyasviel--control_v11f1e_sd15_tile/snapshots/3f877705c37010b7221c3d10743307d6b5b6efac/diffusion_pytorch_model.bin onto cuda backend...
    Generated composition image in 28.5s                                                                                                                                                        
Traceback (most recent call last):
  File "/usr/local/bin/imagine", line 7, in <module>
    imaginairy.cli.imagine.imagine_cmd()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/imaginairy/cli/imagine.py", line 187, in imagine_cmd
    return _imagine_cmd(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/cli/shared.py", line 220, in _imagine_cmd
    filenames = imagine_image_files(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate.py", line 90, in imagine_image_files
    for result in imagine(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate.py", line 237, in imagine
    result = generate_single_image(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate_refiners.py", line 283, in generate_single_image
    controlnet.inject()
  File "/usr/local/lib/python3.10/site-packages/imaginairy/vendored/refiners/foundationals/latent_diffusion/stable_diffusion_1/controlnet.py", line 159, in inject
    assert controlnet not in target_controlnets, f"{controlnet} is already injected"
AssertionError: Controlnet(name=details) is already injected

**Comment by bluusun** [comment]
Using Version 14.1.1
