### ISSUE TITLE
Support for Flux

### ISSUE THREAD

**Issue by tomups** [brycedrennan/imaginAIry#489]
I really love your library! Are you planning to add support for Flux models?

**Comment by brycedrennan** [comment]
I haven't followed them closely but if I understand correctly, they barely run on the 4090 so not sure its worth the time.

**Comment by tomups** [comment]
With FP8 quantization, Flux Dev runs on 16GB VRAM. I'm running it in my 4090 laptop and it's quite good. With 4bit it should run in 8GB but I didn't try it, so not sure about the quality.

I'm using this script https://gist.github.com/AmericanPresidentJimmyCarter/873985638e1f3541ba8b00137e7dacd9

**Comment by brycedrennan** [comment]
Well now with AI coding up things I was able to use the script you provided and get a duct-tape version out the door with imaginairy==15.0.0.  Yeah uses surprisingly little memory.

`imagine "{_landscape-type_|_fruit_|_flower_}. {_style_}"  --model flux --size FHD --upscale -r 20`

https://github.com/brycedrennan/imaginAIry/pull/491

**Comment by tomups** [comment]
Wow that was fast indeed! Thank you so much. If you want to try inpainting controlnets and img2img in the future, they have been recently (3 weeks ago) added to the HF diffusers library 

https://huggingface.co/docs/diffusers/main/api/pipelines/flux#diffusers.FluxImg2ImgPipeline

https://huggingface.co/docs/diffusers/main/api/pipelines/flux#diffusers.FluxControlNetInpaintPipeline

For depth, canny... there is this

https://github.com/XLabs-AI/x-flux

**Comment by bluusun** [comment]
That's what I got... (latest imaginairy) pip3 install -U imaginairy huggingface_hub

magine "{_landscape-type_|_fruit_|_flower_}. {_style_}"  --model flux --size FHD --upscale -r 20
✨ Generate images faster using a persistent shell session. Just run `aimg` to start. This makes generation and editing much quicker since the model can stay loaded in memory.

Generating 20 images. (1 prompt(s) x 20 repetitions)

/usr/local/lib/python3.10/site-packages/xformers/triton/softmax.py:30: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float16 if _triton_softmax_fp16_enabled else None)
/usr/local/lib/python3.10/site-packages/xformers/triton/softmax.py:87: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(
/usr/local/lib/python3.10/site-packages/xformers/ops/swiglu_op.py:78: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  def forward(cls, ctx, x, w1, b1, w2, b2, w3, b3):
/usr/local/lib/python3.10/site-packages/xformers/ops/swiglu_op.py:99: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(cls, ctx, dx5):
🖼  1/20 "canterbury bells. done in lego"
    negative-prompt:DEFAULT-NEGATIVE-PROMPT
    size:1920x1080px-(16:9) seed:634470385 prompt-strength:7.5 steps:5 solver-type:ddim init-image-strength:0.2 arch:flux weights:flux
/usr/local/lib/python3.10/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/imagine", line 7, in <module>
    imaginairy.cli.imagine.imagine_cmd()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/imaginairy/cli/imagine.py", line 190, in imagine_cmd
    return _imagine_cmd(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/cli/shared.py", line 234, in _imagine_cmd
    filenames = imagine_image_files(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate.py", line 88, in imagine_image_files
    for result in imagine(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate.py", line 285, in imagine
    result = generate_func(
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate_flux.py", line 146, in generate_single_image
    ) = load_flux_models()
  File "/usr/local/lib/python3.10/site-packages/imaginairy/api/generate_flux.py", line 51, in load_flux_models
    tokenizer_2 = T5TokenizerFast.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5_fast.py", line 133, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 111, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 960 column 3

**Comment by bluusun** [comment]
Ah followed instructions here:

https://github.com/huggingface/transformers/issues/31789

Followed by pip3 install -U transformers which seem to have gotten the tokenizer version correctly now

**Comment by bluusun** [comment]
Flux images look great!!

Maybe there should be a warning about the huge file size for download and space required. 

Also image-to-image would be awesome (basic might be enough as Flux is much better than SD generally) so Controlnet may not be necessary.
