### ISSUE TITLE
Install error on M1 with grpcio and conda

### ISSUE THREAD

**Issue by hannesa2** [brycedrennan/imaginAIry#61]
"just works" was not valid for me on my M1
With
```
brew install cmake protobuf rust
python3 -m venv env
. env/bin/activate
pip install imaginairy
```
I run into 
```
      creating None/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/tmpzh5sjcuo
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/hannes/miniforge3/include -arch arm64 -fPIC -O2 -isystem /Users/hannes/miniforge3/include -arch arm64 -I/opt/homebrew/opt/openssl@3/include -I/Users/hannes/git/ai/imaginAIry/env/include -I/Users/hannes/miniforge3/include/python3.9 -c /var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/tmpzh5sjcuo/a.c -o None/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/tmpzh5sjcuo/a.o
      Traceback (most recent call last):
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/spawn.py", line 91, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/hannes/git/ai/imaginAIry/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/setup.py", line 540, in <module>
          setuptools.setup(
        File "/Users/hannes/git/ai/imaginAIry/env/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/hannes/git/ai/imaginAIry/env/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/install.py", line 546, in run
          self.run_command('build')
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/Users/hannes/git/ai/imaginAIry/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/commands.py", line 284, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/unixccompiler.py", line 117, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] +
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
          spawn(cmd, dry_run=self.dry_run)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/spawn.py", line 91, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/hannes/git/ai/imaginAIry/env/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/command/build_ext.py", line 529, in build_extension
          objects = self.compiler.compile(sources,
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/hannes/miniforge3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/np/7ckckk8s5fd169kvnnfhjkk40000gr/T/pip-install-bfttvlxs/grpcio_2e6589fc53b54149beaca903ff651a0d/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/hannes/miniforge3/lib/python3.9/distutils/unixccompiler.py", line 120, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by hannesa2** [comment]
Using 

https://github.com/pietrodn/grpcio-mac-arm-build/actions/runs/2981988333 from https://github.com/pietrodn/grpcio-mac-arm-build and run

```
pip install ~/Downloads/artifact/grpcio-1.48.1-cp39-cp39-macosx_11_0_arm64.whl
pip install imaginairy
```

makes it work 👍

**Comment by hannesa2** [comment]
Any idea what was wrong on my side, to fail promise "just works" ?

**Comment by brycedrennan** [comment]
I'm looking into it right now. I appreciate that you provided the error messages.

**Comment by brycedrennan** [comment]
First thing I notice is you're using conda, which admittedly I have not tested with.

**Comment by hannesa2** [comment]
> First thing I notice is you're using conda

Did I ? This was not my intention. How do you see this ?

**Comment by brycedrennan** [comment]
`miniforge3` in the path to a lot of the python files in the stack trace

**Comment by brycedrennan** [comment]
Given that I know someone else installed this today on an M1, I'm inclined to view this as just conda related and close the issue. Let me know if you have any more information.
