### ISSUE TITLE
--fix-faces doesn't work

### ISSUE THREAD

**Issue by adnikiforov** [brycedrennan/imaginAIry#80]
Hello!

I'm using imaginAIry version `4.1.0` installed via pip3. Python 3.10 from Homebrew. MacBook Pro 2021 M1, macOS 12.5. I had Python initially installed via asdf, but I had a problems with the SD, so I've reinstalled it from Homebrew.

When trying to use `--fix-faces`, I'm getting this error

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/cmds.py", line 238, in imagine_cmd
    imagine_image_files(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/api.py", line 74, in imagine_image_files
    for result in imagine(
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/api.py", line 294, in imagine
    img = enhance_faces(img, fidelity=prompt.fix_faces_fidelity)
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/enhancers/face_restoration_codeformer.py", line 56, in enhance_faces
    net = codeformer_model()
  File "/opt/homebrew/lib/python3.10/site-packages/imaginairy/enhancers/face_restoration_codeformer.py", line 28, in codeformer_model
    checkpoint = torch.load(ckpt_path)["params_ema"]
  File "/opt/homebrew/lib/python3.10/site-packages/torch/serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/homebrew/lib/python3.10/site-packages/torch/serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

I've googled a bit and it seems that the problem with the Torch model (I'm not quite into that stuff so bear with me). Any ideas, where to look?

**Comment by brycedrennan** [comment]
Yes I'd guess you previously interrupted a download so now it's trying to read an incomplete zip file. 

You'll need to delete that corrupted zip file and then try again.  It's likely located in `~/.cache/imaginairy/weights`

**Comment by adnikiforov** [comment]
> You'll need to delete that corrupted zip file and then try again. It's likely located in `~/.cache/imaginairy/weights`

Yes! That works, I should've get this by myself. Thanks!
