### ISSUE TITLE
Not enought memory.

### ISSUE THREAD

**Issue by popeye2019** [brycedrennan/imaginAIry#82]
(imaginairi) C:\Users\franc>imagine "A picture of an Icelandic landscape"
🤖🧠 imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
Generating 🖼  1/1: "A picture of an Icelandic landscape" 512x512px seed:495117480 prompt-strength:7.5 steps:40 sampler-
type:plms
Loading model C:\Users\franc/.cache\huggingface\transformers\d12e71b67e29abaf317bf9d0e31644872fd2072509a4b3582cbb0c30f70824e9.98fc1312797017a8bac6993df565908fd18f09319b40d9bd35457dfa1459ecf0 onto cuda backend...
Traceback (most recent call last):
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\franc\anaconda3\envs\imaginairi\Scripts\imagine.exe\__main__.py", line 7, in <module>
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\imaginairy\cmds.py", line 238, in imagine_cmd
    imagine_image_files(
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\imaginairy\api.py", line 74, in imagine_image_files
    for result in imagine(
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\imaginairy\api.py", line 130, in imagine
    model = get_diffusion_model(
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\imaginairy\model_manager.py", line 127, in get_diffusion_model
    model.num_timesteps_cond  # noqa
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\imaginairy\model_manager.py", line 50, in __getattr__
    model = load_model_from_config(
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\imaginairy\model_manager.py", line 98, in load_model_from_config
    model.to(get_device())
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 109, in to
    return super().to(*args, **kwargs)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\torch\nn\modules\module.py", line 987, in to
    return self._apply(convert)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\torch\nn\modules\module.py", line 662, in _apply
    param_applied = fn(param)
  File "C:\Users\franc\anaconda3\envs\imaginairi\lib\site-packages\torch\nn\modules\module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.41 GiB already allocated; 0 bytes free; 3.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

(imaginairi) C:\Users\franc>

[installation imaginAIry.txt](https://github.com/brycedrennan/imaginAIry/files/9968124/installation.imaginAIry.txt)

**Comment by brycedrennan** [comment]
This implies your graphics card only has 4GB of ram. I think you might be able to find a different version of stable diffusion that supports using that little memory but I don't intend to make this one have a smaller memory footprint for the time being.

**Comment by brycedrennan** [comment]
You could also use the colab version: https://colab.research.google.com/drive/1rOvQNs0Cmn_yU1bKWjCOHzGVDgZkaTtO?usp=sharing
