### ISSUE TITLE
The option --show-work does not work

### ISSUE THREAD

**Issue by vepito** [brycedrennan/imaginAIry#84]
Hello,

I understand that --show-work can be used to get an image each time a step is accomplished (please correct me if I'm wrong).

When I add --show-work to the command line, the image generation fails

imagine "text" --precision full --fix-faces --steps 50 --show-work
imaginAIry received 1 prompt(s) and will repeat them 1 times to create 1 images.
Running in CPU mode. it's gonna be slooooooow.
Generating 🖼  1/1: "text" 512x512px seed:187796535 prompt-strength:7.5 steps:27 sampler-type:plms
Loading model /home/g/.cache/huggingface/transformers/d12e71b67e29abaf317bf9d0e31644872fd2072509a4b3582cbb0c30f70824e9.98fc1312797017a8bac6993df565908fd18f09319b40d9bd35457dfa1459ecf0 onto cpu backend...
Traceback (most recent call last):
  File "/home/g/./.local/bin/imagine", line 8, in <module>
    sys.exit(imagine_cmd())
  File "/home/g/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/g/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/g/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/g/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/g/.local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/g/.local/lib/python3.10/site-packages/imaginairy/cmds.py", line 238, in imagine_cmd
    imagine_image_files(
  File "/home/g/.local/lib/python3.10/site-packages/imaginairy/api.py", line 74, in imagine_image_files
    for result in imagine(
  File "/home/g/.local/lib/python3.10/site-packages/imaginairy/api.py", line 246, in imagine
    log_latent(init_latent_noised, "init_latent_noised")
  File "/home/g/.local/lib/python3.10/site-packages/imaginairy/log_utils.py", line 28, in log_latent
    _CURRENT_LOGGING_CONTEXT.log_latents(latents, description)
  File "/home/g/.local/lib/python3.10/site-packages/imaginairy/log_utils.py", line 72, in log_latents
    if latents.shape[1] != 4:
AttributeError: 'NoneType' object has no attribute 'shape'

Do you know why this issue ?

**Comment by brycedrennan** [comment]
I have a fix coming out soon.

**Comment by brycedrennan** [comment]
Fixed in just released 5.0.0
