### ISSUE TITLE
An error occurred while installing imaginairy

### ISSUE THREAD

**Issue by pirboazo** [brycedrennan/imaginAIry#89]
HI 
I try to install imaginairy on GoogleCloud VM with GPU , debian 10.

> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

[imaginairy.log](https://github.com/brycedrennan/imaginAIry/files/9997503/imaginairy.log)

Regards
Pierre

**Comment by brycedrennan** [comment]
the log implies the box doesn't have enough memory. Errors during installation of torch. Appears unrelated to imaginairy.

```
        File "/home/boipisigre/.local/share/virtualenvs/imaginairy-YT0l4Z7y/lib/python3.7/site-packages/pip/_vendor/msgpack/fallback.py", line 403, in _read
          ret = self._buffer[i : i + n]
      MemoryError
      Traceback (most recent call last):
        File "/home/boipisigre/.local/share/virtualenvs/imaginairy-YT0l4Z7y/lib/python3.7/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
```
